- includes/Events.php
- includes/Flows/Upgrades/1.0.0.php
PRESS2-1070 : Replace technically accurate "typography" with more commonly understood "fonts"
> changed typography to fonts

- includes/Patterns.php
- includes/Services/WonderBlocksService.php
**Site Pages Step Before:** Has block grammar from yith-wonder
https://github.com/newfold-labs/wp-module-onboarding-data/assets/38878906/8b1d3c1d-fbed-42ff-b191-04d8195f2afe
**Site Pages Step After:** Has block grammar from wonder blocks
https://github.com/newfold-labs/wp-module-onboarding-data/assets/38878906/2c0c3982-1b2a-4be3-adea-081ab5fe62f3
These will also be published as site pages once the flow is complete.
> Add Wonder Blocks Site Pages

- includes/Flows/Flows.php
- includes/Patterns.php
- includes/Services/WonderBlocksService.php
1. Adds Wonder Block header and footers.
2. Fixes bug where Wonder Blocks headers and footers are missing post Onboarding.
Onboarding PR: https://github.com/newfold-labs/wp-module-onboarding/pull/350
> Add Wonder Blocks Header and Footer support

- includes/Brands.php
- includes/Flows/Flows.php
Fix for brand value HostGator string check.
Enable onboarding for HostGator US
> changes for enabling hostgator US

- composer.json
- composer.lock
- includes/Flows/Flows.php
- includes/Services/SiteGenService.php
Integrates the APIs from [Module AI](https://github.com/newfold-labs/wp-module-ai/commit/623eaabcbcbd691e877ff6f3dce3854cc8cfc202) into Onboarding.
> Integrate APIs to AI Onboarding

- composer.json
- composer.lock
This should fix our PHP lint workflows: https://github.com/newfold-labs/wp-module-data/pull/54
> Update Data Module to 2.4.16

- includes/Options.php
- includes/Services/SiteGenService.php
Fetch Homepage previews
Regenerate Homepage previews
Favourites list
Regenerate favourited previews
> Api integration preview home page

- includes/Flows/Flows.php
for Sitegen error page : https://github.com/newfold-labs/wp-module-onboarding/pull/445
> updated flow

- includes/Plugins.php
Based on the Hiive Flags, a particular subset of plugins will be installed and activated.
> Install Plugins Extended

- includes/Patterns.php
> Fix unnecessary sitemap AI calls

- composer.lock
> Bump Installer, Data and AI

- includes/Plugins.php
Fixes the priorities for various plugins and makes sure woocommerce is the first and foremost plugin to be installed and activated.
> Fix `Priorities`

- includes/Preview.php
> Enhancement: Verify 'Yith Wonder' Theme Activation in Preview & Editor Step

- composer.lock
> Bump AI to 1.1.8

- includes/Flows/Flows.php
> Update flow data version to 2.0.3

- composer.json
- composer.lock
> Bump Data and Patterns

- composer.json
- composer.lock
> Use Major Versions for Patterns

- includes/Data.php
> Change the visibility of the `is_fresh_installation` function to public

- includes/I18n.php
> Add `is_callable` checks

- composer.json
- composer.lock
Remove dependency on coming soon, performance, and install checker modules.
It doesn't appear they are used.
> Remove dependency on some modules

- includes/Events.php
> added migration_initiated

- includes/Flows/Flows.php
- includes/Services/SiteGenService.php
> Limit AI Retries

- includes/Plugins.php
> Change Activation for Yith Plugins

- composer.lock
> Update Onboarding Data to 1.1.10

- composer.lock
> Release 1.1.11

- includes/Patterns.php
This adds a new `key` to the `site-pages` array, which will be used across languages to identify and report events on the site pages step.
This goes with: https://github.com/newfold-labs/wp-module-onboarding/pull/575
> Add keys to `site-pages`

- includes/I18n.php
> Add a more reliable way for translations

- includes/Plugins.php
> Install Woo first for `hasYithExtended` capability

- includes/Flows/Flows.php
> Add Min Char Threshold Site Details

- includes/Data.php
> Integrate Sentry

- composer.json
- composer.lock
> Add the Survey Module

- includes/Flows/Flows.php
> added sitegen theme mode value in the flow

- includes/Plugins.php
JIRA: https://jira.newfold.com/browse/PRESS0-1450
> Install wonder cart when hasYithExtended is true in onboarding screen

- composer.json
- composer.lock
> Bump Onboarding Data to 1.1.14

- includes/Events.php
JIra: https://jira.newfold.com/browse/PRESS0-1764
- Added `mfe_migration_initiated` event
> Find a way to track migration initiated from MFE

- includes/Services/SiteGenService.php
This PR renames the Sitegen toast survey from `wonder_start` to `wonder_start_sitegen_pulse`.
> Rename the Sitegen Toast Survey

- includes/Services/FlowService.php
- includes/Themes.php
- includes/Themes/Fonts.php
Story: https://jira.newfold.com/browse/PRESS0-1919
> Helper Functions and Slugs for Interacting with Flow and Theme Data

- includes/Plugins.php
This PR removes the `hasYithExtended` check for plugin installation.
> Remove `hasYithExtended` check

- includes/Config.php
- includes/Plugins.php
https://jira.newfold.com/browse/PRESS0-1714
> Make Solution compatible with all brands

- README.md
Udpated Module responsibilities and critical path
> added critical path

- includes/Services/SiteGenService.php
The onboarding shows the following fatal error if $plugin_recomendations contains a WP_Error
`PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /Users/carlosrodriguez/Local Sites/vulcan/app/public/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-onboarding-data/includes/Services/SiteGenService.php:684
Stack trace:
`
This PR prevents this issue by first checking if the variable is a WP_Error.
> Fix prevent fatal error if $plugin_recomendations contains a WP_Error

- .github/workflows/lint-check-php.yml
This PR will update the actions/cache to version 4 to prevent workflow failures.
> Update actions/cache to version 4

- includes/Brands.php
- includes/Events.php
- includes/Flows/Flows.php
- includes/Options.php
This PR adds the ability for the users to restart onboarding.
> Restart Onboarding

- includes/Services/SiteGenService.php
Just a small change to avoid fatal error using the method "**purgeAll**" by onboarding date. According the coding standard, the name of that method has been updated in "**purge_all**" in the Performance module.
**IMPORTANT**
It must be released in combination with the version of Performance module which contains [this PR](https://github.com/newfold-labs/wp-module-performance/pull/135).
> Compatibility fix for support on cache code refactoring

- includes/Flows/Flows.php
- includes/Services/SiteGenService.php
> add locale support in site generation

- includes/Config.php
- includes/Plugins.php
- Permissions checking is failing during rest calls. This introduces a more comprehensive permissions checking to include more scenarios.
- Refactor default plugins list to adhere to Products requirements.
Addresses an internal P3: C1115522
> Refactor get_site_capability method permissions

- package-lock.json
- package.json
> Bump `package*` to 1.2.13

- includes/Services/SiteGenService.php
support site_type param passed by the app: https://github.com/newfold-labs/wp-module-onboarding/pull/801
> Support site_type

- includes/Services/SiteGenService.php
In terms of feature delivery, Sitekits are totally independent of Onboarding-data. So this PR only adds `keywords` to the list of identifiers, since the keywords are sent to the service when generating the sitekits.
Currently, `keywords` are only requested when we request home pages, because on the surface, it seems like the call needs `content_tones` but if you inspect the actual API call, we've never sent `content_tones` and only send the prompt.
> Sitekits support

- includes/Options.php
This PR adds new option names to be used in wp-module-onboarding for tracking site info and onboarding time tracking.
Related PR's:
- [saving site info in options table #819](https://github.com/newfold-labs/wp-module-onboarding/pull/819)
- [track start and end time for onboarding #824](https://github.com/newfold-labs/wp-module-onboarding/pull/824)
> added new option names

- composer.json
- composer.lock
- includes/Services/PreviewsService.php
- includes/Services/SiteGenService.php
> Release 1.2.14

- includes/Brands.php
The following PR will implement the link tracker features across different urls [PRESS0-3024](https://jira.newfold.com/browse/PRESS0-3024)
> Implement wp-module-link-tracker features across different URLs

- includes/Options.php
> Add blueprints state to options map array

- includes/Events.php
Whitelist events added in Onboarding v3.2
> whitelist blueprint and site type events
